In [86]:
#1.サンプルデータの取得
import pandas as pd
from sklearn.datasets import load_wine
dataset = load_wine()

df = pd.DataFrame(data=dataset.data,columns=dataset.feature_names)
df['category'] = dataset.target
df.head()
df.shape


(178, 14)

In [85]:
#2.サンプルデータの分割
x = dataset.data
y = dataset.target

from sklearn.model_selection import train_test_split

train_test_split(x,y,test_size=0.3,random_state=5)

[array([[1.358e+01, 2.580e+00, 2.690e+00, ..., 7.400e-01, 1.800e+00,
         7.500e+02],
        [1.234e+01, 2.450e+00, 2.460e+00, ..., 8.000e-01, 3.380e+00,
         4.380e+02],
        [1.285e+01, 3.270e+00, 2.580e+00, ..., 8.700e-01, 2.110e+00,
         5.700e+02],
        ...,
        [1.225e+01, 3.880e+00, 2.200e+00, ..., 6.500e-01, 2.000e+00,
         8.550e+02],
        [1.277e+01, 3.430e+00, 1.980e+00, ..., 7.000e-01, 2.120e+00,
         3.720e+02],
        [1.229e+01, 3.170e+00, 2.210e+00, ..., 1.420e+00, 2.830e+00,
         4.060e+02]]),
 array([[1.387000e+01, 1.900000e+00, 2.800000e+00, 1.940000e+01,
         1.070000e+02, 2.950000e+00, 2.970000e+00, 3.700000e-01,
         1.760000e+00, 4.500000e+00, 1.250000e+00, 3.400000e+00,
         9.150000e+02],
        [1.311000e+01, 1.010000e+00, 1.700000e+00, 1.500000e+01,
         7.800000e+01, 2.980000e+00, 3.180000e+00, 2.600000e-01,
         2.280000e+00, 5.300000e+00, 1.120000e+00, 3.180000e+00,
         5.020000e+02],
       

In [57]:
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.3,random_state=5)
print(x.shape,X_train.shape,X_test.shape,y.shape,Y_train.shape,Y_test.shape)

(178, 13) (124, 13) (54, 13) (178,) (124,) (54,)


In [83]:
#3. 予測モデルのインスタンス化
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(random_state=3)

#4.予測モデルの学習
model.fit(X_train, Y_train)
#5. 予測モデルの評価
y_pred = model.predict(X_test)
y_pred


array([0, 1, 0, 0, 2, 2, 0, 0, 1, 1, 0, 0, 2, 1, 2, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 2, 2, 0, 1, 1, 0, 0, 2, 2, 0, 2, 2, 0, 1, 2, 2, 0,
       2, 1, 0, 2, 0, 1, 0, 1, 1, 0])

In [94]:
#目的変数y（ワインの種別）のテストデータを確認
Y_test

array([0, 1, 0, 0, 2, 2, 0, 0, 1, 0, 0, 0, 2, 1, 2, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 2, 2, 0, 1, 1, 0, 0, 2, 2, 0, 2, 2, 1, 1, 1, 2, 0,
       2, 1, 0, 2, 0, 1, 0, 1, 1, 0])

In [95]:
from sklearn.metrics import accuracy_score
#正解率
accuracy_score(Y_test,y_pred)

0.9259259259259259

In [96]:
#scoreメソッド→分類の予測モデルの場合は正解率が出力され、回帰の予測モデルの場合は決定係数
model.score(X_test,Y_test)

0.9259259259259259

In [80]:
#6.予測
import numpy as np
#ダミーデータを3セット作成
X_real = np.array([
    [13, 1.6, 2.2, 16, 118, 2.6, 2.9, 0.21, 1.6, 5.8, 0.92, 3.2, 1011],
    [12, 2.8, 2.2, 18, 100, 2.5, 2.3, 0.25, 2.0, 2.2, 1.15, 3.3, 1000],
    [14, 4.1, 2.7, 24, 101, 1.6, 0.7, 0.53, 1.4, 9.4, 0.61, 1.6, 560]])

In [81]:
#ワインの成分のダミーデータから、ワインの種別を予測
model.predict(X_real)

array([0, 1, 2])

In [99]:
#ランダムフォレスト

from sklearn.ensemble import RandomForestClassifier
modelR = RandomForestClassifier(random_state=3)
#4.予測モデルの学習
modelR.fit(X_train,Y_train)
#5. 予測モデルの評価
y_pred = modelR.predict(X_test)
#正解率
accuracy_score(Y_test, y_pred)

0.9629629629629629